apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../local

patches:
- path: patch-seed.yaml
  target:
    group: core.gardener.cloud
    kind: Seed
    name: local
    version: v1beta1
