# Secret containing basic auth for remote write of shoot prometheus metrics
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-seed-remote-write-credentials
  namespace: garden
  labels:
    gardener.cloud/role: global-shoot-remote-write-monitoring
type: Opaque
data:
   # Basic Auth
  username: base64(admin)
  password: base64(password)
