apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudprofile1-scheduling-regions
  namespace: garden
  annotations:
    scheduling.gardener.cloud/cloudprofiles: cloudprofile1{,optional-cloudprofile-name-2,...}
  labels:
    scheduling.gardener.cloud/purpose: region-config
data:
  europe-west-1: |
    europe-central-1: 50
    europe-north-1: 60
    europe-south-1: 70
    europe-east-1: 120
    us-west-1: 220
