---
apiVersion: v1
kind: Secret
metadata:
  name: shoot-service-account-issuer
  namespace: garden
  labels:
    gardener.cloud/role: shoot-service-account-issuer
type: Opaque
stringData:
  hostname: discovery.local.gardener.cloud
