apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../registry

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-gcr-io.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-gcr
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-eu-gcr-io.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-gcr-eu
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-ghcr-io.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-ghcr
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-registry-k8s-io.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-k8s
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-quay-io.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-quay
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://registry-europe-docker-pkg-dev.kube-system.svc.cluster.local:5000
    target:
      group: apps
      kind: Deployment
      name: registry-europe-docker-pkg-dev
