apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/sshd

secretGenerator:
- files:
  - host-keys/authorized_keys
  - host-keys/ssh_host_ecdsa_key
  - host-keys/ssh_host_ecdsa_key.pub
  - host-keys/ssh_host_ed25519_key
  - host-keys/ssh_host_ed25519_key.pub
  - host-keys/ssh_host_rsa_key
  - host-keys/ssh_host_rsa_key.pub
  name: gardener-apiserver-sshd-keys
  namespace: relay
