apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway-service-account
  namespace: test-ingress
  labels:
    app.kubernetes.io/version: 1.19.3
    app: istio-ingressgateway
    foo: bar
automountServiceAccountToken: false