apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istiod
  namespace: test
  labels:
    app: istiod
    istio: pilot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istiod
      istio: pilot
  unhealthyPodEvictionPolicy: AlwaysAllow