prometheus:
  replicas: 1
  storage: 20Gi
  networks:
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
    nodes: 10.250.0.0/16
  namespace:
    uid: 100c3bb5-48b9-4f88-96ef-48ed557d4212
  podAnnotations: {}
  images:
    prometheus: image-repository:image-tag
    configmap-reloader: image-repository:image-tag
    vpn-seed: image-repository:image-tag
  ingress:
    class: nginx
  secretNameClusterCA: ca
  secretNameEtcdCA: ca-etcd
  secretNameEtcdClientCert: etcd-client-tls
global:
  shootKubeVersion:
    gitVersion: v1.7.5
