apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/ssh
- namespace.yaml

namespace: relay

secretGenerator:
- files:
  - client-keys/host
  - client-keys/known_hosts
  - client-keys/seed_id_rsa
  - client-keys/seed_id_rsa.pub
  name: gardener-apiserver-ssh-keys
