apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: garden

secretGenerator:
- files:
  - tls/ca.crt
  - tls/server.crt
  - tls/server.key
  name: etcd-tls

resources:
- networkpolicy.yaml
- service.yaml
- statefulset.yaml
labels:
- includeSelectors: true
  pairs:
    app: etcd
