trustDomain: cluster.local
image: to-be-injected-by-imagevector
labels:
  app: istiod
  istio: pilot
deployNamespace: false
priorityClassName: gardener-system-critical
ports:
  https: 10250
portsNames:
  metrics: metrics
serviceName: istiod
