config:
  gardenClientConnection:
    bootstrapKubeconfig:
      kubeconfig: |
        apiVersion: v1
        kind: Config
        current-context: gardenlet-bootstrap
        clusters:
        - cluster:
            insecure-skip-tls-verify: true
            server: https://gardener-local-ha-single-zone-control-plane:6443
          name: default
        contexts:
        - context:
            cluster: default
            user: gardenlet-bootstrap
          name: gardenlet-bootstrap
        users:
        - name: gardenlet-bootstrap
          user:
            token: 07401c.f395accd246ae52d
  seedConfig:
    metadata:
      name: local2-ha-single-zone
      labels:
        base: kind2
    spec:
      ingress:
        domain: ingress.local2-ha-single-zone.seed.local.gardener.cloud
