replicaCount: 2
config:
  seedConfig:
    metadata:
      name: local-ha-multi-zone
    spec:
      provider:
        zones:
        - "0"
        - "1"
        - "2"
      ingress:
        domain: ingress.local-ha-multi-zone.seed.local.gardener.cloud
      settings:
        topologyAwareRouting:
          enabled: true
nodeToleration:
  defaultNotReadyTolerationSeconds: 60
  defaultUnreachableTolerationSeconds: 60

