apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | trim | indent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
{{ .Values.labels | toYaml | trim | indent 6 }}
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
