{{- if .Values.global.gardenlet.vpa }}
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: gardenlet-vpa
  namespace: garden
spec:
  {{- if .Values.global.gardenlet.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: {{ required ".Values.global.gardenlet.vpa.resourcePolicy.minAllowed.cpu is required" .Values.global.gardenlet.vpa.resourcePolicy.minAllowed.cpu }}
          memory: {{ required ".Values.global.gardenlet.vpa.resourcePolicy.minAllowed.memory is required" .Values.global.gardenlet.vpa.resourcePolicy.minAllowed.memory }}
  {{- end }}
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: gardenlet
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 200Mi
{{- end }}
