apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-kind-network
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/description: Allows egress from pods labeled with 'networking.gardener.cloud/to-kind-network=allowed'
      to all containers in the kind docker network. This can be used for example for allowing egress to the garden
      cluster from the second kind cluster.
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-kind-network: allowed
  egress:
  - to:
    - ipBlock:
        cidr: 172.18.0.0/16
    - ipBlock:
        cidr: fd00:10::/64
  policyTypes:
  - Egress
