{{- define "containerd-endpoint-conf" -}}
{{- if .Values.worker.cri.endpoints -}}
- path: /etc/containerd/runtime_ske.toml
  permissions: 0644
  content:
    inline:
      encoding: ""
      data: |
        [plugins]
          [plugins."io.containerd.grpc.v1.cri"]
            [plugins."io.containerd.grpc.v1.cri".registry]
              [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
{{- range $ep := .Values.worker.cri.endpoints }}
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ $ep.name }}"]
                  endpoint = ["{{ $ep.endpoint }}"]
{{- end }}
              [plugins."io.containerd.grpc.v1.cri".registry.configs]
{{- range $ep := .Values.worker.cri.endpoints }}
                [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ $ep.name }}".tls]
                  insecure_skip_verify = {{ default "false" $ep.insecureSkipVerify }}
{{- end }}
{{- end -}}
{{- end -}}