apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /etc/gardener/local-registry/localhost
  target:
    group: apps
    kind: Deployment
    name: registry
labels:
- includeSelectors: true
  pairs:
    upstream: none
