apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry


resources:
- namespace.yaml
- gcr
- gcr-eu
- ghcr
- k8s
- localhost
- quay
- europe-docker-pkg-dev
labels:
- includeSelectors: true
  pairs:
    app: registry
