{{- $ingVersion := (include "ingressversion" .) }}
apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Chart.Name }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      {{- if eq $ingVersion "networking.k8s.io/v1" }}
      - backend:
          service:
            name: prometheus-web
            port:
              number: 80
        pathType: Prefix
        path: /
      {{- else }}
      - backend:
          serviceName: prometheus-web
          servicePort: 80
        path: /
      {{- end }}
  {{- end }}
