apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: prometheus
    role: monitoring
  sessionAffinity: None
  type: ClusterIP
---
